In [1]:
import numpy as np
from scipy.linalg import expm

A = np.array([[1,1,0],
             [0,0,2],
             [0,0,-1]])
A = np.asmatrix(A)
print(A)
print(expm(A))

[[ 1  1  0]
 [ 0  0  2]
 [ 0  0 -1]]
[[2.71828183 1.71828183 1.08616127]
 [0.         1.         1.26424112]
 [0.         0.         0.36787944]]


In [2]:
H = np.ones((2,2), dtype=np.complex_)
R = np.ones((2,2), dtype=np.complex_)
H = [[1/2*np.pi,0],[0,-1/2*np.pi]]

for i in range(0, 5):
    R = np.dot(np.dot(-1j,H),i/100.0)
    U = expm(R)
    U = np.asmatrix(U)
    U_dagger = U.getH()
    print(U)
    print("=========")

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[0.99987663-0.01570732j 0.        +0.j        ]
 [0.        +0.j         0.99987663+0.01570732j]]
[[0.99950656-0.03141076j 0.        +0.j        ]
 [0.        +0.j         0.99950656+0.03141076j]]
[[0.99888987-0.04710645j 0.        +0.j        ]
 [0.        +0.j         0.99888987+0.04710645j]]
[[0.99802673-0.06279052j 0.        +0.j        ]
 [0.        +0.j         0.99802673+0.06279052j]]


In [3]:
ts = np.linspace(0, 10, 1000)

PSI_0 = np.ones((2,2), dtype=np.complex_)
PSI_0 = [[0.80],[0.60]]
PSI_1 = np.ones((2,2), dtype=np.complex_)
PSI_1 = [[0.40],[0.916]]
H = np.ones((2,2), dtype=np.complex_)
ro = 0.65*np.matmul(PSI_0, np.transpose(PSI_0))+0.35*np.matmul(PSI_1, np.transpose(PSI_1))

for i in range(0, 5):
    
    H = [[np.exp(-1j*np.pi*i/2),0],[0,np.exp(1j*np.pi*i/2)]]
    U = H
    U = np.asmatrix(U)
    U_dagger = U.getH()
    print("-----------")
    print(f"{i}pi")
    print(np.matmul(np.matmul(U,ro),U_dagger))
    print("-----------")

-----------
0pi
[[0.472    +0.j 0.44024  +0.j]
 [0.44024  +0.j 0.5276696+0.j]]
-----------
-----------
1pi
[[ 0.472    +0.00000000e+00j -0.44024  -5.39138507e-17j]
 [-0.44024  +5.39138507e-17j  0.5276696+0.00000000e+00j]]
-----------
-----------
2pi
[[0.472    +0.00000000e+00j 0.44024  +1.07827701e-16j]
 [0.44024  -1.07827701e-16j 0.5276696+0.00000000e+00j]]
-----------
-----------
3pi
[[ 0.472    +0.00000000e+00j -0.44024  -1.61741552e-16j]
 [-0.44024  +1.61741552e-16j  0.5276696+0.00000000e+00j]]
-----------
-----------
4pi
[[0.472    +0.00000000e+00j 0.44024  +2.15655403e-16j]
 [0.44024  -2.15655403e-16j 0.5276696+0.00000000e+00j]]
-----------


In [4]:
def dpsi_dt(t, ro, H): # A derivada da ro em relação ao tempo não tem dependência temporal
    A = np.zeros((2,2), dtype=np.complex_)
    ro = np.asmatrix(ro)
    A =  (H*ro)-(ro*H) # [H,p]
    return -1j*A

# Runge-Kutta de quarta ordem

def runge_kutta(ro, fator_runge_kutta, hamiltoniano, tempo_inicial = 0):
    
    k1 = dpsi_dt(tempo_inicial, ro, hamiltoniano)
    k2 = dpsi_dt(tempo_inicial + 0.5 * fator_runge_kutta, ro + 0.5*fator_runge_kutta*k1, hamiltoniano)
    k3 = dpsi_dt(tempo_inicial + 0.5 * fator_runge_kutta, ro + 0.5*fator_runge_kutta*k2, hamiltoniano)
    k4 = dpsi_dt(tempo_inicial + fator_runge_kutta, ro + 0.5*fator_runge_kutta*k3, hamiltoniano)
    
    ## y(i+1) = y(i) + h/6*(k1+2*k2+2*k3+k4)
    
    A = (np.dot(2,k3) + k4)
    B = (np.dot(2,k2) + k1)
    C = (A + B)

    runge = ro + np.dot((fator_runge_kutta / 6.0),(C))
        
    return runge

H = [[-1/2*np.pi,0],[0,1/2*np.pi]]
for i in range(0, 200):

    teste = runge_kutta(ro, 0.01, H)
    print("-----------")
    print(teste)
    print("-----------")
    ro = teste
    

-----------
[[0.472     +0.j         0.44005897+0.01382884j]
 [0.44005897-0.01382884j 0.5276696 +0.j        ]]
-----------
-----------
[[0.472     +0.j         0.43944362+0.02764631j]
 [0.43944362-0.02764631j 0.5276696 +0.j        ]]
-----------
-----------
[[0.472     +0.j         0.43839448+0.04143877j]
 [0.43839448-0.04143877j 0.5276696 +0.j        ]]
-----------
-----------
[[0.472     +0.j        0.43691253+0.0551926j]
 [0.43691253-0.0551926j 0.5276696 +0.j       ]]
-----------
-----------
[[0.472     +0.j         0.43499916+0.06889422j]
 [0.43499916-0.06889422j 0.5276696 +0.j        ]]
-----------
-----------
[[0.472     +0.j        0.43265617+0.0825301j]
 [0.43265617-0.0825301j 0.5276696 +0.j       ]]
-----------
-----------
[[0.472     +0.j         0.42988582+0.09608678j]
 [0.42988582-0.09608678j 0.5276696 +0.j        ]]
-----------
-----------
[[0.472     +0.j         0.42669076+0.10955087j]
 [0.42669076-0.10955087j 0.5276696 +0.j        ]]
-----------
-----------
[[0.472     

In [5]:
#TODO Looping com MPC