In [1]:
import numpy as np
from scipy.linalg import expm

A = np.array([[1,1,0],
             [0,0,2],
             [0,0,-1]])
A = np.asmatrix(A)
print(A)
print(expm(A))

[[ 1  1  0]
 [ 0  0  2]
 [ 0  0 -1]]
[[2.71828183 1.71828183 1.08616127]
 [0.         1.         1.26424112]
 [0.         0.         0.36787944]]


In [2]:
H = np.ones((2,2), dtype=np.complex_)
R = np.ones((2,2), dtype=np.complex_)
H = [[1/2*np.pi,0],[0,3/2*np.pi]]

for i in range(0, 5):
    R = np.dot(np.dot(-1j,H),i/100.0)
    U = expm(R)
    U = np.asmatrix(U)
    U_dagger = U.getH()
    print(U)
    print("=========")

[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[0.99987663-0.01570732j 0.        +0.j        ]
 [0.        +0.j         0.99888987-0.04710645j]]
[[0.99950656-0.03141076j 0.        +0.j        ]
 [0.        +0.j         0.99556196-0.09410831j]]
[[0.99888987-0.04710645j 0.        +0.j        ]
 [0.        +0.j         0.99002366-0.14090123j]]
[[0.99802673-0.06279052j 0.        +0.j        ]
 [0.        +0.j         0.98228725-0.18738131j]]


In [3]:
ts = np.linspace(0, 10, 1000)

PSI = np.ones((2,2), dtype=np.complex_)
PSI = [[0.80],[0.60]]
H = np.ones((2,2), dtype=np.complex_)
R = np.ones((2,2), dtype=np.complex_)
H = [[1/2*np.pi,0],[0,3/2*np.pi]]
R = [[0,0],[0,0]]
ro = np.matmul(PSI, np.transpose(PSI))

for i in range(0, 1000):

    R = np.dot(np.dot(-1j,H),i/100.0)
    U = expm(R)
    U = np.asmatrix(U)
    U_dagger = U.getH()
    print("-----------")
    print(np.matmul(np.matmul(U,ro),U_dagger))
    print("-----------")

-----------
[[0.64+0.j 0.48+0.j]
 [0.48+0.j 0.36+0.j]]
-----------
-----------
[[0.64      +0.j         0.47976315+0.01507716j]
 [0.47976315-0.01507716j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47905283+0.03013945j]
 [0.47905283-0.03013945j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +3.46944695e-18j 0.47786974+4.51719904e-02j]
 [0.47786974-4.51719904e-02j 0.36      +6.93889390e-18j]]
-----------
-----------
[[0.64      +0.j         0.47621506+0.06015995j]
 [0.47621506-0.06015995j 0.36      +0.j        ]]
-----------
-----------
[[0.64     +0.j         0.4740904+0.07508854j]
 [0.4740904-0.07508854j 0.36     +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47149788+0.08994303j]
 [0.47149788-0.08994303j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.46844005+0.10470876j]
 [0.46844005-0.10470876j 0.36      +0.j        ]]
-----------
-----------
[[0.64      -1.38777878e-17j 0.46491992+1.193711

In [4]:
def dpsi_dt(t, ro, H): # A derivada da ro em relação ao tempo não tem dependência temporal
    A = np.zeros((2,2), dtype=np.complex_)
    ro = np.asmatrix(ro)
    A =  (H*ro)-(ro*H) # [H,p]
    return -1j*A

# Runge-Kutta de quarta ordem

def runge_kutta(ro, fator_runge_kutta, hamiltoniano, tempo_inicial = 0):
    
    k1 = dpsi_dt(tempo_inicial, ro, hamiltoniano)
    k2 = dpsi_dt(tempo_inicial + 0.5 * fator_runge_kutta, ro + 0.5*fator_runge_kutta*k1, hamiltoniano)
    k3 = dpsi_dt(tempo_inicial + 0.5 * fator_runge_kutta, ro + 0.5*fator_runge_kutta*k2, hamiltoniano)
    k4 = dpsi_dt(tempo_inicial + fator_runge_kutta, ro + 0.5*fator_runge_kutta*k3, hamiltoniano)
    
    ## y(i+1) = y(i) + h/6*(k1+2*k2+2*k3+k4)
    
    A = (np.dot(2,k3) + k4)
    B = (np.dot(2,k2) + k1)
    C = (A + B)

    runge = ro + np.dot((fator_runge_kutta / 6.0),(C))
        
    return runge

for i in range(0, 1000):

    teste = runge_kutta(ro, 0.01, H)
    print("-----------")
    print(teste)
    print("-----------")
    ro = teste
    

-----------
[[0.64      +0.j         0.47980262+0.01507778j]
 [0.47980262-0.01507778j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47913169+0.03014317j]
 [0.47913169-0.03014317j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47798781+0.04518128j]
 [0.47798781-0.04518128j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47637202+0.06017728j]
 [0.47637202-0.06017728j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47428583+0.07511636j]
 [0.47428583-0.07511636j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j         0.47173124+0.08998376j]
 [0.47173124-0.08998376j 0.36      +0.j        ]]
-----------
-----------
[[0.64      +0.j        0.46871069+0.1047648j]
 [0.46871069-0.1047648j 0.36      +0.j       ]]
-----------
-----------
[[0.64      +0.j         0.46522707+0.11944488j]
 [0.46522707-0.11944488j 0.36      +0.j        ]]
-----------
-----------
[[0.64  

In [5]:
#TODO Looping com MPC