## Proposta

Encontrar os valores dos campos de controle, $f_x$, $f_y$ e $f_z$. Os valores de controle podem ser definidos como: $$f_{x,y,z}=-a_{x,y,z}S(A_{x,y,z},t) - h_{x,y,z}\frac{S(B,t)}{S(A_{x,y,z},t)}$$

$S$ é a representação do controle de Lyapunov já que este consiste nas componentes que formam a derivada de $V(t)$, cujo o propósito, em Lyapunov, é ser menor que zero enquanto $V(t)$ deve ser maior que zero, em qualquer tempo. $S$ pode ser definido como: $$S(X,t)=(-\frac{1}{2}U_t^{\dagger}X^{\dagger}U_fW^{\dagger}-\frac{1}{2}W^{\dagger}U_t^{\dagger}X^{\dagger}U_f+2U_t^{\dagger}X^{\dagger}U_f)L$$

Para começar os trabalhos, iniciamos em $t=0$ pois como $U$ é a evolução temporal unitária, $U_0 = diag(1,1,1)$, ademais, $X \in \{A_x, A_y, A_z, B\}$, $U_f=\left(\begin{array}{cc} 
0 & 0 & 1\\
0 & -1 & 0\\
1 & 0 & 0\\
\end{array}\right)$, $h_x+h_y+h_z = 1$. O $A's$ e $B$ são matrizes que foram obtidas por meio da transformação adjunta em $SO(3)$ da equação mestra de Lindblad, por fim, $W_t = U_f^{\dagger}U_t$ e por consequência $L_t = W_t - I -\frac{1}{2}(W_t-I)^2$.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize
import random

In [2]:
def lyap(Ui, Uf, X):
    #first=-1/2*np.matmul(np.matmul(np.matmul(Ui.getH(),X.getH()),Uf),np.matmul(Uf.getH(), Ui).getH())
    second=-1*np.matmul(np.matmul(Uf.getH(), Ui).getH(), np.matmul(np.matmul(Ui.getH(),X.getH()),Uf))
    third=2*np.matmul(np.matmul(Ui.getH(),X.getH()),Uf)
    L=np.subtract(np.matmul(Uf.getH(), Ui), np.identity(3))-1/2*np.subtract(np.matmul(Uf.getH(), Ui), np.identity(3))**2
    return 2*np.trace((second+third)*L)
    #return (first+second+third)*L

def control(Ui, Uf, a, h, A, B):
    SA=lyap(Ui, Uf, A)
    SB=lyap(Ui, Uf, B)
    return -a*SA-h*(SB/SA)

# U' = (A(t)+B)U
def dUdt(u, Ui, Uf, t):
    Ax = np.matrix('0 0 0; 0 0 -1; 0 1 0')
    Ay = np.matrix('0 0 1; 0 0 0; -1 0 0')
    Az = np.matrix('0 -1 0; 1 0 0; 0 0 0')
    B = 0.01*np.matrix('-1 0 0; 0 -1 0; 0 0 -2')
    if t == 0:
        F = np.dot(10.28, Ax)+np.dot(10.73, Ay)+np.dot(40, Az)
    else:
        fx = control(Ui, Uf, u[0], u[3], Ax, B)
        fy = control(Ui, Uf, u[1], u[4], Ay, B)
        fz = control(Ui, Uf, u[2], u[5], Az, B)
        F = np.dot(fx, Ax)+np.dot(fy, Ay)+np.dot(fz,Az)+B
    return np.matmul(F, Ui)

# Runge-Kutta de quarta ordem

def runge_kutta(u, Ui, Uf, h, t):
    
    k1 = dUdt(u, Ui, Uf, t)
    k2 = dUdt(u, Ui + np.dot((0.5*h), k1), Uf, t)
    k3 = dUdt(u, Ui + np.dot((0.5*h), k2), Uf, t)
    k4 = dUdt(u, Ui + np.dot(h, k3), Uf, t)
    
    A = np.dot(2,k3) + k4
    B = np.dot(2,k2) + k1
    C = A+B

    res = Ui + np.dot((h / 6.0),(C))
        
    return res

In [3]:
def func_objetivo(u, Ui, Uf, h, t):
    return np.linalg.norm(np.subtract(Uf, runge_kutta(u, Ui, Uf, h, t)))

In [4]:
def const(u): #h_x+h_y+h_z=1
    return u[3] + u[4] + u[5] - 1

def main():
    
    # Instância
    cons = {'type':'eq', 'fun': const}
    u = []
    # a's
    u.append(70)
    u.append(106)
    u.append(66)
    
    #h's
    u.append(0.35)
    u.append(0.31)
    u.append(0.34)

    h = 0.001 #Runge-kutta

    t = 0

    Ui = np.matrix('1 0 0; 0 1 0; 0 0 1')
    Uf = np.matrix('0 0 1; 0 -1 0; 1 0 0')

    while t <= 100:

        Ui = runge_kutta(u, Ui, Uf, h, t)
        print(f'U_{t}: {Ui}')
        print(f'Fidelity: {((np.trace(np.matmul(Ui, Ui.getH())))+np.abs(np.trace(np.matmul(Uf.getH(), Ui)))**2)/(2*(2+1))}')
        print(f'Distance: {np.trace((Ui - Uf).getH()*(Ui - Uf))}')
        print("----------------")

        t = t + 1

    

In [5]:
main()

U_0: [[ 0.99914256 -0.03993272  0.01093231]
 [ 0.04004301  0.99914729 -0.01006231]
 [-0.01052117  0.01049145  0.99988961]]
Fidelity: 0.6662456503897921
Distance: 7.997472305028497
----------------
U_1: [[ 0.98489257 -0.16895748  0.01553977]
 [ 0.16942585  0.97323839 -0.14700536]
 [ 0.01096525  0.14751907  0.98831535]]
Fidelity: 0.6485439309036957
Distance: 7.888426251641331
----------------
U_2: [[ 0.69174189 -0.6394209   0.30542285]
 [ 0.63123274  0.3734027  -0.64949761]
 [ 0.32107503  0.64146183  0.68149838]]
Fidelity: 0.4972400339506721
Distance: 5.413192667568175
----------------
U_3: [[ 0.26542465 -0.60205203  0.7367893 ]
 [ 0.57235882 -0.49645998 -0.61140484]
 [ 0.75935487  0.58232411  0.23750947]]
Fidelity: 1.1443769326430664
Distance: 1.9105820106057125
----------------
U_4: [[ 0.12321521 -0.43275667  0.87951236]
 [ 0.39988383 -0.77449606 -0.43625969]
 [ 0.89475733  0.40382215  0.10166439]]
Fidelity: 1.5660469357195135
Distance: 0.8025432026015593
----------------
U_5: [[ 0.069