## Proposta

Encontrar os valores dos campos de controle, $f_x$, $f_y$ e $f_z$. Os valores de controle podem ser definidos como: $$f_{x,y,z}=-a_{x,y,z}S(A_{x,y,z},t) - h_{x,y,z}\frac{S(B,t)}{S(A_{x,y,z},t)}$$

$S$ é a representação do controle de Lyapunov já que este consiste nas componentes que formam a derivada de $V(t)$, cujo o propósito, em Lyapunov, é ser menor que zero enquanto $V(t)$ deve ser maior que zero, em qualquer tempo. $S$ pode ser definido como: $$S(X,t)=(-\frac{1}{2}U_t^{\dagger}X^{\dagger}U_fW^{\dagger}-\frac{1}{2}W^{\dagger}U_t^{\dagger}X^{\dagger}U_f+2U_t^{\dagger}X^{\dagger}U_f)L$$

Para começar os trabalhos, iniciamos em $t=0$ pois como $U$ é a evolução temporal unitária, $U_0 = diag(1,1,1)$, ademais, $X \in \{A_x, A_y, A_z, B\}$, $U_f=\left(\begin{array}{cc} 
0 & 0 & 1\\
0 & -1 & 0\\
1 & 0 & 0\\
\end{array}\right)$, $h_x+h_y+h_z = 1$. O $A's$ e $B$ são matrizes que foram obtidas por meio da transformação adjunta em $SO(3)$ da equação mestra de Lindblad, por fim, $W_t = U_f^{\dagger}U_t$ e por consequência $L_t = W_t - I -\frac{1}{2}(W_t-I)^2$.


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize
import random

In [2]:
def lyap(Ui, Uf, X):
    #first=-1/2*np.matmul(np.matmul(np.matmul(Ui.getH(),X.getH()),Uf),np.matmul(Uf.getH(), Ui).getH())
    second=-1*np.matmul(np.matmul(Uf.getH(), Ui).getH(), np.matmul(np.matmul(Ui.getH(),X.getH()),Uf))
    third=2*np.matmul(np.matmul(Ui.getH(),X.getH()),Uf)
    L=np.subtract(np.matmul(Uf.getH(), Ui), np.identity(3))-1/2*np.subtract(np.matmul(Uf.getH(), Ui), np.identity(3))**2
    return 2*np.trace((second+third)*L)
    #return (first+second+third)*L

def control(Ui, Uf, a, h, A, B):
    SA=lyap(Ui, Uf, A)
    SB=lyap(Ui, Uf, B)
    return -a*SA-h*(SB/SA)

# U' = (A(t)+B)U
def dUdt(u, Ui, Uf, t):
    Ax = np.matrix('0 0 0; 0 0 -1; 0 1 0')
    Ay = np.matrix('0 0 1; 0 0 0; -1 0 0')
    Az = np.matrix('0 -1 0; 1 0 0; 0 0 0')
    B = 0.01*np.matrix('-1 0 0; 0 -1 0; 0 0 -2')
    if t == 0:
        F = np.dot(10.28, Ax)+np.dot(10.73, Ay)+np.dot(40, Az)
    else:
        fx = control(Ui, Uf, u[0], u[3], Ax, B)
        fy = control(Ui, Uf, u[1], u[4], Ay, B)
        fz = control(Ui, Uf, u[2], u[5], Az, B)
        F = np.dot(fx, Ax)+np.dot(fy, Ay)+np.dot(fz,Az)+B
    return np.matmul(F, Ui)

# Runge-Kutta de quarta ordem

def runge_kutta(u, Ui, Uf, h, t):
    
    k1 = dUdt(u, Ui, Uf, t)
    k2 = dUdt(u, Ui + np.dot((0.5*h), k1), Uf, t)
    k3 = dUdt(u, Ui + np.dot((0.5*h), k2), Uf, t)
    k4 = dUdt(u, Ui + np.dot(h, k3), Uf, t)
    
    A = np.dot(2,k3) + k4
    B = np.dot(2,k2) + k1
    C = A+B

    res = Ui + np.dot((h / 6.0),(C))
        
    return res

In [3]:
def func_objetivo(u, Ui, Uf, h, t):
    return np.linalg.norm(np.subtract(Uf, runge_kutta(u, Ui, Uf, h, t)))

In [4]:
def const(u): #h_x+h_y+h_z=1
    return u[3] + u[4] + u[5] - 1

def main():
    
    # Instância
    cons = {'type':'eq', 'fun': const}
    u = []
    # a's
    u.append(70)
    u.append(106)
    u.append(66)
    
    #h's
    u.append(0.35)
    u.append(0.31)
    u.append(0.34)

    h = 0.001 #Runge-kutta

    t = 0

    Ui = np.matrix('1 0 0; 0 1 0; 0 0 1')
    Uf = np.matrix('0 0 1; 0 -1 0; 1 0 0')

    print(f'U_{t}: {Ui}')
    print(f'Norm: {np.linalg.norm(np.subtract(Uf, Ui))}')
    print(f'Fidelity: {(np.trace(np.matmul(Ui, Ui.getH()))+np.abs(np.trace(np.matmul(Uf.getH(), Ui)))**2)/(3*(3+1))}')
    print(f'Distance: {np.trace((Ui - Uf).getH()*(Ui - Uf))}')

    while t < 0.1:

        Ui = runge_kutta(u, Ui, Uf, h, t)
        for i in range(0,3):
            for j in range(0,3):
                Ui[i, j] = round(Ui[i, j], 3)
        print(f'U_{round(t+0.001, 3)}: {Ui}')
        print(f'Norm: {np.linalg.norm(np.subtract(Uf, Ui))}')
        print(f'Fidelity: {(np.trace(np.matmul(Ui, Ui.getH()))+np.abs(np.trace(np.matmul(Uf.getH(), Ui)))**2)/(3*(3+1))}')
        print(f'Distance: {np.trace((Ui - Uf).getH()*(Ui - Uf))}')
        print("----------------")

        t = round(t+0.001, 3)

    

In [5]:
main()

U_0: [[1 0 0]
 [0 1 0]
 [0 0 1]]
Norm: 2.8284271247461903
Fidelity: 0.3333333333333333
Distance: 8
U_0.001: [[ 0.999 -0.04   0.011]
 [ 0.04   0.999 -0.01 ]
 [-0.011  0.01   1.   ]]
Norm: 2.828010608183781
Fidelity: 0.3331370833333333
Distance: 7.997644000000001
----------------
U_0.002: [[ 0.985 -0.168  0.016]
 [ 0.169  0.973 -0.146]
 [ 0.01   0.146  0.989]]
Norm: 2.8087093121218505
Fidelity: 0.32430475
Distance: 7.888847999999999
----------------
U_0.003: [[ 0.694 -0.637  0.305]
 [ 0.631  0.378 -0.648]
 [ 0.318  0.64   0.684]]
Norm: 2.330227242137556
Fidelity: 0.248332
Distance: 5.429959
----------------
U_0.004: [[ 0.266 -0.602  0.737]
 [ 0.574 -0.494 -0.612]
 [ 0.758  0.583  0.238]]
Norm: 1.3847317429740678
Fidelity: 0.5709669166666665
Distance: 1.9174819999999997
----------------
U_0.005: [[ 0.123 -0.433  0.88 ]
 [ 0.401 -0.773 -0.437]
 [ 0.894  0.404  0.101]]
Norm: 0.8972012037441769
Fidelity: 0.7821815833333333
Distance: 0.80497
----------------
U_0.006: [[ 0.069 -0.316  0.934]
 